apiVersion: apps/v1
kind: Deployment
metadata:
  name: gs-service
spec:
  selector:
    matchLabels:
      app: gs-service
  template:
    spec:
      containers:
        - name: gs-service
          image: dmitry4excalibursolutions/odos-gs:0.0.2